# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 06:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_assets', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('debt_pc', models.FloatField(default=0)),
                ('equity_pc', models.FloatField(default=0)),
                ('cash_pc', models.FloatField(default=0)),
                ('other_pc', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FundCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
                ('num_funds', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amc_code', models.CharField(max_length=3, verbose_name='AMC Code')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('total_aum', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('fax', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FundScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('objective', models.CharField(blank=True, max_length=1000)),
                ('aum', models.FloatField(blank=True, null=True)),
                ('aum_date', models.DateField(blank=True, null=True)),
                ('fund_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fund_category_list', to='funds.FundCategory')),
                ('fund_house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fund_house_list', to='funds.FundHouse')),
            ],
        ),
        migrations.CreateModel(
            name='SchemePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bse_code', models.CharField(blank=True, max_length=15)),
                ('rta_code', models.CharField(blank=True, max_length=10)),
                ('amc_code', models.CharField(blank=True, max_length=10)),
                ('isin', models.CharField(blank=True, max_length=15)),
                ('if_direct', models.NullBooleanField(default=False)),
                ('if_growth', models.NullBooleanField(default=False)),
                ('if_open', models.NullBooleanField(default=True)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('asset_size', models.FloatField(blank=True, null=True)),
                ('asset_size_date', models.DateField(blank=True, null=True)),
                ('expense_ratio', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('expense_ratio_date', models.DateField(blank=True, null=True)),
                ('nav_latest', models.FloatField(blank=True, null=True)),
                ('nav_latest_date', models.DateField(blank=True, null=True)),
                ('dividend_history', models.CharField(blank=True, max_length=1000)),
                ('fund_scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheme_plan_list', to='funds.FundScheme')),
            ],
        ),
        migrations.AddField(
            model_name='assetportfolio',
            name='fund_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='funds.FundCategory'),
        ),
        migrations.AddField(
            model_name='assetportfolio',
            name='fund_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='funds.FundScheme'),
        ),
    ]
