# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 05:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetportfolio',
            options={'verbose_name_plural': 'Asset Portfolios'},
        ),
        migrations.AlterModelOptions(
            name='fundcategory',
            options={'verbose_name_plural': 'Fund Categories'},
        ),
        migrations.AlterModelOptions(
            name='fundhouse',
            options={'verbose_name_plural': 'Fund Houses'},
        ),
        migrations.AlterModelOptions(
            name='fundscheme',
            options={'verbose_name_plural': 'Fund Schemes'},
        ),
        migrations.AlterModelOptions(
            name='schemeplan',
            options={'verbose_name_plural': 'Scheme Plans'},
        ),
    ]
