# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 07:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20171102_0705'),
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('P', 'Purchase'), ('R', 'Redemption'), ('A', 'Additional Purchase')], default='P', max_length=1)),
                ('order_type', models.CharField(choices=[('1', 'Lumpsum'), ('2', 'SIP')], default='1', max_length=1)),
                ('status', models.CharField(choices=[('0', 'Requested internally'), ('1', 'Cancelled/Failed- refer to status_comment for reason'), ('2', 'Order successfully placed at BSE'), ('4', 'Redirected after payment'), ('5', 'Payment provisionally made'), ('6', 'Order sucessfully completed at BSE'), ('7', 'Reversed'), ('8', 'Concluded')], default='0', max_length=1)),
                ('status_comment', models.CharField(blank=True, max_length=1000)),
                ('amount', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('scheme_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', related_query_name='transaction', to='funds.SchemePlan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', related_query_name='transaction', to='users.Info')),
            ],
        ),
    ]
